image_size_index: 50
max_length_name: 128
max_length_email: 255
min_length_password: 6
remember: "1"
department:
  division_1: 1
  division_2: 2
  division_3: 3
  back_officer: 4
  human_resource: 5
  internal_comunicator: 6
  education: 7

device_status:
  using: 1
  available: 2
  broken: 3

user_role:
  admin: 1
  manager: 2
  staff: 3
all : "All"
none: "None"

request_status:
  cancelled: 1
  waiting_approve: 2
  approved: 3
  done: 4
type:
  request: 1
device_code:
  max_length: 4
  append_character: "0"
notification:
  max_display: 20
email:
  parameter:
    from_email: "email"
history_type:
  request: 1
  device: 2
dms_history_data:
  field:
    content: "content"
    status: "status"
entry:
  request: "Request"
  assignment: "Assignment"
action:
  create: "Create"
  read: "Read"
  update: "Update"
  delete: "Delete"
  approve: "Approve"
  created: "Created"
  updated: "Updated"
