image_size_index: 50
max_length_name: 128
max_length_email: 255
min_length_password: 6
remember: "1"
department:
  division_1: 1
  division_2: 2
  division_3: 3
  back_officer: 4
  human_resource: 5
  internal_comunicator: 6
  education: 7

device_status:
  using: 1
  available: 2
  broken: 3

user_role:
  admin: 1
  manager: 2
  staff: 3
all : "All"
none: "None"
type:
  request: 1
device_code:
  max_length: 4
  append_character: "0"
notification:
  max_display: 20
  request_path: "/requests"
email:
  parameter:
    from_email: "email"
history_type:
  request: 1
  device: 2
dms_history_data:
  field:
    content: "content"
    status: "status"
entry:
  request: "Request"
  assignment: "Assignment"
  admin: "Admin"
  device: "Device"
request_status:
  cancelled: 1
  waiting_approve: 2
  approved: 3
  waiting_done: 4
  done: 5

action:
  create: "Create"
  read: "Read"
  update: "Update"
  delete: "Delete"
  approve: "Approve"
  waiting_done: "Waiting Done"
  done: "Done"
  created: "Created"
  updated: "Updated"
mailer_host: "localhost:3000"
user_setting:
  send_mail_notification: "send_mail_notification"
  page_size: "page_size"
  user_signal: "user_signal"
  order_by_unread_notification: "order_by_unread_notification"
  quantity_load_notification: "quantity_load_notification"
  setting_type:
    default: "type=\"text\""
    page_size: "onblur=\"minmax(this, 5, 30)\""
    quantity_load_notification: "onblur=\"minmax(this, 5, 30)\""
paging:
  page_size: 15
  min_page_size: 5
  max_page_size: 30
  page_size_dashboard: 6
top_dashboard: 5
dashboard:
  request:
    backgroundColor: ['#BDC3C7', '#9B59B6', '#E74C3C', '#26B99A', '#3498DB']
    hoverBackgroundColor: ['#CFD4D8', '#B370CF', '#E95E4F', '#36CAAB', '#49A9EA']
    colors: ["aero", "purple",  "red", "green", "blue"]
    type: "doughnut"
  device:
    backgroundColor: ['#BDC3C7', '#9B59B6', '#E74C3C']
    hoverBackgroundColor: ['#CFD4D8', '#B370CF', '#E95E4F']
    colors: ["aero", "purple",  "red"]
    type: "doughnut"
chart_type:
  request: "1"
  device: "2"
boolean_params:
  true: "1"
  false: "0"
languages:
  japan: "jp"
  english: "en"
allowedExtension:
  device: ["csv", "xls", "xlsx"]
column_file:
  import_device:
    device_code: "device code"
    invoice: "invoice"
    production_name: "production name"
    model_number: "model number"
    serial_number: "serial number"
    last_using_by: "last using by"
    description: "description"
import:
  default_message:
    assigment_description: "Create by auto import"
  first_row: 1
  start_row: 2
  user:
    column:
      div_group_name: 9
      sec_group_name: 10
      lead_group_name: 11
      user_name: 6
      user_office_email: 44
      office_name: 13
  type:
    user: "User"
    device: "Device"
  admin_group: "Admin"
optional:
  crud: "{\"Create\":true,\"Read\":true,\"Update\":true,\"Delete\":true}"
  approve: "{\"Approve\":true}"
  waiting_done: "{\"Waiting Done\":true}"
  done: "{\"Done\":true}"
special_group_name:
  back_office_manage: "Back Office"
  general_affairs: "General Affairs"
position:
  ga_office: "GA Officer"
  division_manager: "Divison Manager"
  section_manager: "Section Manager"
default_password: "framgia"
user_setting_default: "{\"send_mail_notification\":true,\"order_by_unread_notification\":true,\"quantity_load_notification\":30,\"page_size\":15}"
